EDDI = "eddi"
ZAPPI = "zappi"
HARVI = "harvi"
DEVICE_TYPES = [EDDI, ZAPPI, HARVI]
CT_GENERATION = "Generation"
CT_BATTERY = "AC Battery"
CT_LOAD = "Internal Load"
CT_MONITOR = "Monitor"
CT_GRID = "Grid"
